/* Neo Leaf NeOS
   FIRMWARE: v21.127 Alpha (May 7th, 2021)
   HARDWARE: v21.144 RC1 (May 24th, 2021)
   COMPANY: Neo Leaf Networks
   DEVELOPER: Dominic M. Luciano, Kripanshu Kumar

   Day Numbers Generated By: https://www.epochconverter.com/daynumbers

   CHANGE LOG:
   21.048: Began adding basic functionality and setup procedures
   21.051: Continued adding ands modifying setup and initialization code
   21.052: Finished setup/init code. Added EEPROM read/write functionality
   21.060: Added Access Point Functionality. Bug getting status
   21.062: Continued adding wireless functionality
   21.072: Completed WiFi Access Point functionality
   21.073: Started adding WiFi management functionality
   21.076: Continued adding WiFi management functionality
   21.109:
   21.112: WiFi management functionality functional
   21.116: Rearranged and optimized code
   21.297: Structuring the code and Adding SPI File System
   21.299:  Structuring the Code
   21.301: Added the Flash Storage and the SPIFFS
   21.302: Added the AsynWebserver and the TaskHandler
   21.305: Added the UPnP functionality to the existing system
   21.308: Inter device communication and data exchange
   21.327: Display of online device on web interface
   21.344: Improvement of WiFiConfig menu->adding next button, showing connected network using, live update of device connection, staying on ssame page even if the device is not connectd
   21.345: Creating the HTML page for Neo-Leaf network
           -> Showing the available online networks
           -> Providing interface to select any existing network or creating a new network
   21.350: Adding the exid option to exit the parameters of the network
           -> Dynamically updating the list of available networks
           -> Dynamically updating the variables of the network on the webpage (Operating voltage, user plan, user allowance, etc)
   21.353: Adding the software support to dynamically update the lists and variables of network from the ESP8266 end
           -> Editing the neoLeaf config page
           -> Seperating neoleaf device specific parameters from the common network params
           -> Dynamically updating the values of common network params
           -> Adding option to use the network paras as default for the device params
           
   ERROR CODES:
   A01: Stored FirstRun variable is not 0 or 1. It will be reset to 0 before soft reset.
   B01: WiFi Access Point Activation Has Failed.
   B02: WiFi AP connection has timed out. Device will try again
   B03: WiFi AP connection has timed out three times. This triggers a device reset

*/

//=========================================LOCAL HEADER FILES==============================================
#include "variables.h"
#include "httpUpdates.h"
#include "UPnP.h"
#include "NeoNetwork.h"
#include "HTMLPages.h"
#include "FlashStorage.h"
#include "Wireless.h"
#include "NeoDevices.h"
#include "functions.h"


void setup() {
  // Put your setup code here, to run once:
  Serial.begin(115200);

  initializeParameters();
  initStorage();
  ServerSetup();
  FirstRunCheck();


}

void loop() {
  // put your main code here, to run repeatedly:
  if (millis() - t >= 2000) {
    Serial.println("\n==================================================================");
    Serial.print("\nThe Heap Size is as follow: ");
    Serial.println(ESP.getFreeHeap());
    update_from_ssdp_list();
    Serial.println("\n==================================================================");
    t = millis();
    while (tcp_tw_pcbs != NULL) {
      tcp_abort(tcp_tw_pcbs);
    }
    //runUpdate();
  }
  //deviceList = NULL;
  deviceList = SSDP_UPDATE_LIST();
  get_online_networks(deviceList);
  reconnectWiFi();
  update_power_consumptions();
  delay(10);
}
